# Generated by Django 4.2 on 2023-04-11 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSaude',
            fields=[
                ('id_infosaude', models.AutoField(primary_key=True, serialize=False)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=5)),
                ('pressao_arterial', models.TextField(default='', max_length=7)),
                ('pressao_sistolica', models.IntegerField(max_length=3)),
                ('pressao_diastolica', models.IntegerField(max_length=3)),
                ('nivel_oxigenio_sangue', models.IntegerField(max_length=2)),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=3)),
                ('frequencia_cardiaca', models.IntegerField(max_length=3)),
                ('frequencia_respiratoria', models.IntegerField(max_length=2)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
