# Generated by Django 4.2 on 2023-04-13 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoSaude', '0004_infosaude_glicemia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosaude',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='infosaude',
            name='frequencia_cardiaca',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='infosaude',
            name='frequencia_respiratoria',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='infosaude',
            name='glicemia',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='infosaude',
            name='nivel_oxigenio_sangue',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='infosaude',
            name='peso',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='infosaude',
            name='pressao_arterial',
            field=models.CharField(default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='infosaude',
            name='pressao_diastolica',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='infosaude',
            name='pressao_sistolica',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='infosaude',
            name='temperatura',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
