# Generated by Django 4.2 on 2023-04-11 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RG',
            fields=[
                ('id_rg', models.AutoField(primary_key=True, serialize=False)),
                ('rg', models.CharField(default='', max_length=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataNascimento',
            fields=[
                ('id_datanascimento', models.AutoField(primary_key=True, serialize=False)),
                ('datanascimento', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CPF',
            fields=[
                ('id_cpf', models.SmallAutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(default='', max_length=14)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
