# Generated by Django 4.2 on 2023-04-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_alter_cpf_id_cpf_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpf',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='rg',
            name='rg',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='num_telefone',
            field=models.CharField(max_length=17),
        ),
    ]
