# Generated by Django 4.2 on 2023-04-11 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id_remedio', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RemedioPaciente',
            fields=[
                ('id_remediopaciente', models.AutoField(primary_key=True, serialize=False)),
                ('qtd_vezes_dia', models.IntegerField()),
                ('intervelo_tempo', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(default=django.utils.timezone.now)),
                ('remedio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Remedios.remedio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
