# Generated by Django 4.2 on 2023-04-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remedios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedio',
            name='descricao',
            field=models.TextField(max_length=200),
        ),
    ]
