# Generated by Django 4.2 on 2023-04-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remedios', '0002_alter_remedio_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedio',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
    ]
