# Generated by Django 4.2 on 2023-04-13 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Remedios', '0003_alter_remedio_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediopaciente',
            name='remedio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Remedios.remedio'),
        ),
    ]
